name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      browser-instrumentation-release_created: ${{ steps.release.outputs['packages/instrumentation--release_created'] }}
    steps:
      - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ vars.OTELBOT_BROWSER_APP_ID }}
          private-key: ${{ secrets.OTELBOT_BROWSER_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}

  npm-publish:
    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: package.json
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npm run build

      - run: npm run validate

      - name: Publish @opentelemetry/browser-instrumentation
        if: needs.release-please.outputs.browser-instrumentation-release_created == 'true'
        run: npm publish --workspace=packages/instrumentation --provenance --access public
